// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VertButton: typeof import('vert-editor')['VertButton']
    VertColumnResize: typeof import('vert-editor')['VertColumnResize']
    VertEditor: typeof import('vert-editor')['VertEditor']
  }
}
